<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Scrutor" Version="6.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebAGK.Shared.Abstractions\WebAGK.Shared.Abstractions.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="InfrastructureTests" />
    <InternalsVisibleTo Include="WebAGK.Bootstraper" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="DAL\Migrations\" />
    <Folder Include="Types\" />
  </ItemGroup>


</Project>
