// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAGK.Module.Insurers.Core.DAL;

#nullable disable

namespace WebAGK.Module.Insurers.Core.DAL.Migrations
{
    [DbContext(typeof(InsurersDbContext))]
    [Migration("20250320085557_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Insurers")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Agents", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Insurer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StructureId");

                    b.ToTable("Insurers", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Structure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Structure", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Shared.Infrastructure.Entities.Node<WebAGK.Module.Insurers.Core.Entities.Agent>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Left")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Right")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StructureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ValueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StructureId");

                    b.HasIndex("ValueId");

                    b.ToTable("Nodes", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Insurer", b =>
                {
                    b.HasOne("WebAGK.Module.Insurers.Core.Entities.Structure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("WebAGK.Shared.Infrastructure.Entities.Node<WebAGK.Module.Insurers.Core.Entities.Agent>", b =>
                {
                    b.HasOne("WebAGK.Shared.Infrastructure.Entities.Node<WebAGK.Module.Insurers.Core.Entities.Agent>", "Parent")
                        .WithMany("Nodes")
                        .HasForeignKey("ParentId");

                    b.HasOne("WebAGK.Module.Insurers.Core.Entities.Structure", null)
                        .WithMany("Nodes")
                        .HasForeignKey("StructureId");

                    b.HasOne("WebAGK.Module.Insurers.Core.Entities.Agent", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId");

                    b.Navigation("Parent");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Structure", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("WebAGK.Shared.Infrastructure.Entities.Node<WebAGK.Module.Insurers.Core.Entities.Agent>", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
