// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAGK.Module.Insurers.Core.DAL;

#nullable disable

namespace WebAGK.Module.Insurers.Core.DAL.Migrations
{
    [DbContext(typeof(InsurersDbContext))]
    partial class InsurersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Insurers")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Agents", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Insurer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConcurrencyStamp")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Insurers", "Insurers");
                });

            modelBuilder.Entity("WebAGK.Module.Insurers.Core.Entities.Insurer", b =>
                {
                    b.OwnsMany("WebAGK.Module.Insurers.Core.Entities.Node", "Structure", b1 =>
                        {
                            b1.Property<Guid>("InsurerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Left")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("ParentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Right")
                                .HasColumnType("integer");

                            b1.HasKey("InsurerId", "AgentId");

                            b1.HasIndex("AgentId");

                            b1.HasIndex("ParentId");

                            b1.ToTable("Structure", "Insurers");

                            b1.HasOne("WebAGK.Module.Insurers.Core.Entities.Agent", "Agent")
                                .WithMany()
                                .HasForeignKey("AgentId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("InsurerId");

                            b1.HasOne("WebAGK.Module.Insurers.Core.Entities.Agent", "Parent")
                                .WithMany()
                                .HasForeignKey("ParentId");

                            b1.Navigation("Agent");

                            b1.Navigation("Parent");
                        });

                    b.Navigation("Structure");
                });
#pragma warning restore 612, 618
        }
    }
}
