<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\WebAGK.Shared.Infrastructure\WebAGK.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DAL\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WebAGK.Module.Employees.Api" />
  </ItemGroup>
  
</Project>
